spring:
  application:
    name: eureka-provider
server:
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/ #指明服务注册到该地址
  instance:
      instance-id: eureka-provider #修改euraka默认描述信息
info:
  app.name: test
  company.name: test
  author.name: wyf
