spring:
  application:
    name: eureka-provider
server:
  port: 7004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/ #指明服务注册到该地址
info:
  app.name: test
  company.name: test
  author.name: wyf
