spring:
  application:
    name: eureka-consumer
server:
  port: 7003
eureka:
  instance:
    hostname: localhost #Eureka服务端实例名称
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7000/eureka/