spring:
  application:
    name: hystrix
server:
  port: 7006
eureka:
  client:
#    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream